{"name": "test_google", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Sarang\\.wdm\\drivers\\chromedriver\\win32\\101.0.4951.41\\chromedriver.exe unexpectedly exited. Status code was: 3221225794", "trace": "request = <SubRequest 'test_setup' for <Function test_google>>\n\n    @pytest.fixture(scope=\"class\")\n    def test_setup(request):\n        options = Options()\n        options.add_argument(\"start-maximized\")\n        options.add_experimental_option('excludeSwitches', ['enable-logging'])\n        global driver\n>       driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n\nconftest.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nD:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py:70: in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\nD:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py:90: in __init__\n    self.service.start()\nD:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\common\\service.py:98: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.chrome.service.Service object at 0x000001FAE08D2DD0>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Sarang\\.wdm\\drivers\\chromedriver\\win32\\101.0.4951.41\\chromedriver.exe unexpectedly exited. Status code was: 3221225794\n\nD:\\My projects\\python-pytest\\lib\\site-packages\\selenium\\webdriver\\common\\service.py:110: WebDriverException"}, "attachments": [{"name": "log", "source": "99c94532-fe60-47b5-887c-b984a128ec91-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "0646a08d-8671-44a3-af07-48b3992e629e-attachment.txt", "type": "text/plain"}], "start": 1652510903394, "stop": 1652510903394, "uuid": "ec2515f0-d849-4377-8fd4-bcd69b4fd90c", "historyId": "82ff1ed4bc71b24e7ccd7356e64ba564", "testCaseId": "fda9bc8c8f2b59df65a3d279c2163401", "fullName": "tests.google_test.TestGoogle#test_google", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "google_test"}, {"name": "subSuite", "value": "TestGoogle"}, {"name": "host", "value": "DESKTOP-RD9F5N9"}, {"name": "thread", "value": "11020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.google_test"}]}